name: tourism-recommendation-system
channels:
- anaconda
- conda-forge
- defaults
- bioconda
dependencies:
    - tqdm
    - ipywidgets
    - widgetsnbextension
    - jupyterlab
    - pandas
    - flask
    - pyyaml
    - pip:
        - neo4j
